const airportCodes = [
  { code: 'HAN', name: 'Nội Bài International Airport, Hà Nội' },
  { code: 'SGN', name: 'Tân Sơn Nhất International Airport, Hồ Chí Minh' },
  { code: 'DAD', name: 'Đà Nẵng International Airport, Đà Nẵng' },
  { code: 'PQC', name: 'Phú Quốc International Airport, Phú Quốc' },
  { code: 'CXR', name: 'Cam Ranh International Airport, Nha Trang' },
  { code: 'HUI', name: 'Phú Bài International Airport, Huế' },
  { code: 'BKK', name: 'Suvarnabhumi Airport, Bangkok, Thái Lan' },
  { code: 'HKG', name: 'Hong Kong International Airport, Hồng Kông' },
  { code: 'ICN', name: 'Incheon International Airport, Seoul, Hàn Quốc' },
  { code: 'NRT', name: 'Narita International Airport, Tokyo, Nhật Bản' },
  { code: 'KIX', name: 'Kansai International Airport, Osaka, Nhật Bản' },
  { code: 'SIN', name: 'Changi Airport, Singapore' },
  { code: 'TLH', name: 'Taiwan Taoyuan International Airport, Đài Loan' },
  { code: 'DEL', name: 'Indira Gandhi International Airport, New Delhi, Ấn Độ' },
  { code: 'BOM', name: 'Chhatrapati Shivaji Maharaj International Airport, Mumbai, Ấn Độ' },
  { code: 'DXB', name: 'Dubai International Airport, Dubai, UAE' },
  { code: 'DOH', name: 'Hamad International Airport, Doha, Qatar' },
  { code: 'MNL', name: 'Ninoy Aquino International Airport, Manila, Philippines' },
  { code: 'KUL', name: 'Kuala Lumpur International Airport, Malaysia' },
  { code: 'REP', name: 'Siem Reap International Airport, Campuchia' },
  { code: 'PNH', name: 'Phnom Penh International Airport, Campuchia' },
  { code: 'BWN', name: 'Brunei International Airport, Brunei' },
  { code: 'KHH', name: 'Kaohsiung International Airport, Đài Loan' },
  { code: 'TPE', name: 'Taipei Taoyuan International Airport, Đài Loan' },
  { code: 'HKT', name: 'Phuket International Airport, Thái Lan' },
  { code: 'CJU', name: 'Jeju International Airport, Hàn Quốc' },
  { code: 'KTM', name: 'Tribhuvan International Airport, Kathmandu, Nepal' },
  { code: 'DAC', name: 'Hazrat Shahjalal International Airport, Dhaka, Bangladesh' },
  { code: 'MAA', name: 'Chennai International Airport, Chennai, Ấn Độ' },
  { code: 'DMK', name: 'Don Mueang International Airport, Bangkok, Thái Lan' },
  { code: 'NAG', name: 'Dr. Babasaheb Ambedkar International Airport, Nagpur, Ấn Độ' },
  { code: 'SYD', name: 'Sydney Kingsford Smith Airport, Sydney, Úc' },
  { code: 'MEL', name: 'Melbourne Airport, Melbourne, Úc' },
  { code: 'AKL', name: 'Auckland Airport, Auckland, New Zealand' },
  { code: 'LAX', name: 'Los Angeles International Airport, Los Angeles, USA' },
  { code: 'JFK', name: 'John F. Kennedy International Airport, New York, USA' },
  { code: 'SFO', name: 'San Francisco International Airport, San Francisco, USA' },
  { code: 'ORD', name: 'O Hare International Airport, Chicago, USA' },
  { code: 'SEA', name: 'Seattle-Tacoma International Airport, Seattle, USA' },
  { code: 'YVR', name: 'Vancouver International Airport, Vancouver, Canada' },
  { code: 'YYZ', name: 'Toronto Pearson International Airport, Toronto, Canada' },
  { code: 'LHR', name: 'Heathrow Airport, London, UK' },
  { code: 'CDG', name: 'Charles de Gaulle Airport, Paris, France' },
  { code: 'FRA', name: 'Frankfurt Airport, Frankfurt, Germany' },
  { code: 'AMS', name: 'Amsterdam Schiphol Airport, Amsterdam, Netherlands' },
  { code: 'MAD', name: 'Adolfo Suárez Madrid–Barajas Airport, Madrid, Spain' },
  { code: 'BCN', name: 'Barcelona–El Prat Airport, Barcelona, Spain' },
  { code: 'FCO', name: 'Leonardo da Vinci–Fiumicino Airport, Rome, Italy' },
  { code: 'MXP', name: 'Milan Malpensa Airport, Milan, Italy' },
  { code: 'GRU', name: 'São Paulo/Guarulhos–Governador André Franco Montoro International Airport, São Paulo, Brazil' },
  { code: 'GIG', name: 'Rio de Janeiro/Galeão–Antonio Carlos Jobim International Airport, Rio de Janeiro, Brazil' },
  { code: 'LIM', name: 'Jorge Chávez International Airport, Lima, Peru' },
  { code: 'BOG', name: 'El Dorado International Airport, Bogotá, Colombia' },
  { code: 'EZE', name: 'Ministro Pistarini International Airport, Buenos Aires, Argentina' },
  { code: 'SCL', name: 'Comodoro Arturo Merino Benítez International Airport, Santiago, Chile' },
  { code: 'MEX', name: 'Mexico City International Airport, Mexico City, Mexico' },
  { code: 'CUN', name: 'Cancún International Airport, Cancún, Mexico' },
  { code: 'PTY', name: 'Tocumen International Airport, Panama City, Panama' },
  { code: 'GUA', name: 'La Aurora International Airport, Guatemala City, Guatemala' },
  { code: 'SAL', name: 'El Salvador International Airport, San Salvador, El Salvador' },
  { code: 'SAP', name: 'Ramón Villeda Morales International Airport, San Pedro Sula, Honduras' },
  { code: 'SJO', name: 'Juan Santamaría International Airport, San José, Costa Rica' },
  { code: 'HAV', name: 'José Martí International Airport, Havana, Cuba' },
  { code: 'MBJ', name: 'Sangster International Airport, Montego Bay, Jamaica' },
  { code: 'KIN', name: 'Norman Manley International Airport, Kingston, Jamaica' },
  { code: 'POS', name: 'Piarco International Airport, Port of Spain, Trinidad and Tobago' },
  { code: 'GEO', name: 'Cheddi Jagan International Airport, Georgetown, Guyana' },
  { code: 'PBM', name: 'Johan Adolf Pengel International Airport, Paramaribo, Suriname' },
  { code: 'UIO', name: 'Mariscal Sucre International Airport, Quito, Ecuador' },
  { code: 'GYE', name: 'José Joaquín de Olmedo International Airport, Guayaquil, Ecuador' },
  { code: 'LPB', name: 'El Alto International Airport, La Paz, Bolivia' },
  { code: 'VVI', name: 'Viru Viru International Airport, Santa Cruz, Bolivia' },
  { code: 'ASU', name: 'Silvio Pettirossi International Airport, Asunción, Paraguay' },
  { code: 'MVD', name: 'Carrasco International Airport, Montevideo, Uruguay' },
  { code: 'SJU', name: 'Luis Muñoz Marín International Airport, San Juan, Puerto Rico' },
  { code: 'STT', name: 'Cyril E. King Airport, Saint Thomas, U.S. Virgin Islands' },
  { code: 'STX', name: 'Henry E. Rohlsen Airport, Saint Croix, U.S. Virgin Islands' },
  { code: 'ANU', name: 'V. C. Bird International Airport, Antigua and Barbuda' },
  { code: 'BGI', name: 'Grantley Adams International Airport, Barbados' },
  { code: 'AUA', name: 'Queen Beatrix International Airport, Aruba' },
  { code: 'CUR', name: 'Hato International Airport, Curaçao' },
  { code: 'BON', name: 'Flamingo International Airport, Bonaire' },
  { code: 'SXM', name: 'Princess Juliana International Airport, Sint Maarten' },
  { code: 'PTP', name: 'Pointe-à-Pitre International Airport, Guadeloupe' },
  { code: 'FDF', name: 'Martinique Aimé Césaire International Airport, Martinique' },
  { code: 'GND', name: 'Maurice Bishop International Airport, Grenada' },
  { code: 'TAB', name: 'A.N.R. Robinson International Airport, Tobago' },
  { code: 'EIS', name: 'Terrance B. Lettsome International Airport, Tortola, British Virgin Islands' },
  { code: 'SKB', name: 'Robert L. Bradshaw International Airport, Saint Kitts and Nevis' },
  { code: 'SLU', name: 'George F. L. Charles Airport, Saint Lucia' },
  { code: 'UVF', name: 'Hewanorra International Airport, Saint Lucia' },
  { code: 'GCM', name: 'Owen Roberts International Airport, Grand Cayman, Cayman Islands' },
  { code: 'PLS', name: 'Providenciales International Airport, Turks and Caicos Islands' },
  { code: 'BDA', name: 'L.F. Wade International Airport, Bermuda' },
  { code: 'FPO', name: 'Grand Bahama International Airport, Freeport, Bahamas' },
  { code: 'GGT', name: 'Exuma International Airport, Great Exuma, Bahamas' },
  { code: 'ELH', name: 'North Eleuthera Airport, Eleuthera, Bahamas' }
];

export default airportCodes;
